# Generated by Django 3.2.8 on 2021-10-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquidea', '0002_auto_20211014_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orquidea',
            name='duracion_flor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orquidea',
            name='floracion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orquidea',
            name='tamaño_flor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orquidea',
            name='tipo_crecimiento',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orquidea',
            name='ubicacion',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
